imu0: "imu/data"

imu0_config: [
              false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false
             ]

imu0_differential: true
imu0_relative: false

imu0_remove_gravitational_acceleration: false
