odom0: "odom"

odom0_config: [
               false, false, false,
               false, false, false,
               true,  true,  false,
               false, false, true,
               false, false, false
              ]

odom0_differential: true
odom0_relative: false
