#!/bin/bash

[ -z $1 ] && echo "Missing destination IP" && exit -1

HOST_IP=$1

raspivid -n -w 640 -h 480 -b 1000000 -fps 40 -t 0 -o - | gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay config-interval=10 pt=96 ! udpsink host=$HOST_IP port=9000
