publish_tf: false  # TODO (@eborghi10): Enable
invert_tf: false

# Matcher params
nms_n: 3
nms_tau: 50
match_binsize: 50
match_radius: 200
match_disp_tolerance: 2
outlier_disp_tolerance: 5
outlier_flow_tolerance: 5
multi_stage: 1
half_resolution: 1
refinement: 2
ref_frame_change_method: 2

# Bucketing params
max_features: 2
bucket_width: 50
bucket_height: 50

# Mono params
camera_height: 0.23
camera_pitch: 0.0
ransac_iters: 2000
inlier_threshold: 1e-5
motion_threshold: 100
