<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ca_description)/urdf/utils/inertias.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/create_base_gazebo.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/create_battery.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/create_caster_wheel.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/create_wheel.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/cliff_sensors.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/imu_sensor.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/omni_sensor.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/wall_sensor.xacro"/>

  <xacro:macro name="create_base" params="wheel_separation wheel_radius wheel_width base_diameter *mesh">

    <xacro:property name="caster_radius" value="0.018"/>
    <xacro:property name="base_offset_z" value="${wheel_radius}"/>
    <xacro:property name="base_height"   value="0.0611632"/>
    <xacro:property name="base_mass"     value="2"/>

    <xacro:arg name="visualize" default="false"/>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${base_offset_z}"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>

    <xacro:property name="base_link_origin" value="0 0 ${base_offset_z - caster_radius}"/>

    <link name="base_link">
      <visual>
        <origin xyz="${base_link_origin}"/>
        <geometry>
          <xacro:insert_block name="mesh" />
        </geometry>
      </visual>
    </link>

    <joint name="bumper_joint" type="continuous">
      <parent link="base_link"/>
      <child link="bumper_link"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="bumper_link">
      <xacro:inertial_cylinder_with_pose mass="${base_mass}" radius="${base_diameter/2}" length="${base_height}">
        <origin xyz="${base_link_origin}"/>
      </xacro:inertial_cylinder_with_pose>

      <collision>
        <origin xyz="${base_link_origin}"/>
        <geometry>
          <xacro:insert_block name="mesh" />
        </geometry>
      </collision>
    </link>

    <xacro:wall_sensor>
      <origin xyz="0.09 -0.12 0.042" rpy="0 0 -1"/>
    </xacro:wall_sensor>

    <xacro:cliff_sensor name="side_left_cliff_sensor">
      <origin xyz="0.07 0.14 -0.01" rpy="0 ${pi/2 - 0.09} 0"/>
    </xacro:cliff_sensor>

    <xacro:cliff_sensor name="side_right_cliff_sensor">
      <origin xyz="0.07 -0.14 -0.01" rpy="0 ${pi/2 - 0.09} 0"/>
    </xacro:cliff_sensor>

    <xacro:cliff_sensor name="front_left_cliff_sensor">
      <origin xyz="0.15 0.04 -0.01" rpy="0 ${pi/2 - 0.09} 0"/>
    </xacro:cliff_sensor>

    <xacro:cliff_sensor name="front_right_cliff_sensor">
      <origin xyz="0.15 -0.04 -0.01" rpy="0 ${pi/2 - 0.09} 0"/>
    </xacro:cliff_sensor>

    <xacro:omni_sensor>
      <origin xyz="0.145 0 0.0308"/>
    </xacro:omni_sensor>

    <xacro:wheel name="wheel_left" radius="${wheel_radius}" width="${wheel_width}">
      <origin xyz="0 ${wheel_separation/2} ${base_offset_z}" rpy="0 ${pi/2} ${pi/2}"/>
    </xacro:wheel>
    <xacro:wheel name="wheel_right" radius="${wheel_radius}" width="${wheel_width}">
      <origin xyz="0 ${-wheel_separation/2} ${base_offset_z}" rpy="0 ${pi/2} ${pi/2}"/>
    </xacro:wheel>

    <xacro:property name="caster_z" value="${-caster_radius}"/>
    <xacro:caster_wheel radius="${caster_radius}">
      <origin xyz="0.13 0 ${caster_z}"/>
    </xacro:caster_wheel>

    <xacro:battery_sensor namespace="${robot_name}">
      <origin xyz="0.085 0 ${base_height}"/>
    </xacro:battery_sensor>

    <!-- Simulation sensors -->
    <xacro:sim_create_base/>

    <transmission name="transmission">
      <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel_left_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
   </transmission>
    <transmission name="transmission">
      <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel_right_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
   </transmission>
  </xacro:macro>
</robot>
