transform_tolerance: 0.25
robot_radius: 0.095
track_unknown_space: true   # true needed for disabling global path planning through unknown space
raytrace_range: 3.0
footprint_padding: 0.0

inflation_layer:
  enabled: true
  inflation_radius: 0.5     # max. distance from an obstacle at which costs are incurred for planning paths.
  cost_scaling_factor:  12  # exponential rate at which the obstacle cost drops off (default: 10)
  inflate_unknown: true

obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 5.5
  combination_method: 1
  observation_sources: bump scan
  bump: {
    data_type: PointCloud2,
    topic: mobile_base/sensors/bumper_pointcloud,
    marking: true,
    clearing: false,
    min_obstacle_height: 0.0,
    max_obstacle_height: 0.1
  }
  scan: {
      data_type: LaserScan,
      marking: true,
      clearing: true,
      obstacle_range: 6.0,
      raytrace_range: 10.0,
      min_obstacle_height: -0.1,
      max_obstacle_height: 6
  }

static_layer:
  enabled: true
  map_topic: /map
  subscribe_to_updates: true