global_costmap:

  global_frame: "map"

  # Rate parameters
  update_frequency: 1.0
  publish_frequency: 0.5

  publish_voxel_map: true

  # Map management parameters
  width: 30.0
  height: 30.0
  resolution: 0.01

  static_layer:
    map_topic: "/map"

  plugins:
    # Order matters!
    - {name: static_layer,    type: "costmap_2d::StaticLayer" }
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer" }
