base_global_planner: "jps/JumpPointSearchROS"

JumpPointSearchROS:
  debug: false
  dmp:
    potential_radius:
      x: 1.5
      y: 1.5
    search_radius:
      x: 1.0
      y: 1.0
    potential_map_range:
      x: 10.0
      y: 10.0
