local_costmap:

  # Rate parameters
  publish_frequency: 2.0
  update_frequency: 5.0

  # Map management parameters
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05

  plugins:
    # Order matters!
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer" }
    - {name: inflation_layer, type: "costmap_2d::InflationLayer" }
