# global planner
# The name of the plugin for the global planner to use with move_base.
# This plugin must adhere to the nav_core::BaseGlobalPlanner interface
# specified in the nav_core package.
#
# http://wiki.ros.org/nav_core#BaseGlobalPlanner

# Move base
base_global_planner: "navfn/NavfnROS"

# Move base flex
planners:
  - name: 'NavfnROS'
    type: 'navfn/NavfnROS'

NavfnROS:
  # Publish potential for rviz as pointcloud2, not really helpful, default false
  visualize_potential: false
  # Specifies whether or not to allow navfn to create plans that traverse unknown space, default true
  # Needs to have track_unknown_space: true in the obstacle / voxel layer (in costmap_commons_param) to work
  allow_unknown: true

  # Specifies the x size of an optional window to restrict the planner to, default 0.0
  planner_window_x: 0.0
  # Specifies the y size of an optional window to restrict the planner to, default 0.0
  planner_window_y: 0.0

  # If the goal is in an obstacle, the planer will plan to the nearest point in the radius of default_tolerance, default 0.0
  # The area is always searched, so could be slow for big values
  default_tolerance: 0.0
